//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int id { get; set; }
        public string issue_name { get; set; }
        public string description { get; set; }
        public string issued_by { get; set; }
        public Nullable<System.DateTime> issue_time { get; set; }
        public string status { get; set; }
    }
}
